In [2]:
import pandas as pd
import dask.dataframe as dd

In [3]:
tf = pd.read_csv("Trips_Full Data.csv")

In [4]:
td = pd.read_csv("Trips_by_Distance.csv")

In [5]:
# commands to know more about datasets 
td.head()           # displays first 5 rows

,Level,Date,State FIPS,State Postal Code,County FIPS,County Name,Population Staying at Home,Population Not Staying at Home,Number of Trips,Number of Trips <1,...,Number of Trips 5-10,Number of Trips 10-25,Number of Trips 25-50,Number of Trips 50-100,Number of Trips 100-250,Number of Trips 250-500,Number of Trips >=500,Row ID,Week,Month
0,National,1/1/2019,NaN,NaN,NaN,NaN,77433867.0,248733553.0,8.977844e+08,241667151.0,...,129670778.0,116904343.0,40432062.0,15686639.0,7525563.0,1806022.0,1728112.0,00-00000-20190101,0,1
1,National,1/2/2019,NaN,NaN,NaN,NaN,61305201.0,264862219.0,1.139452e+09,291276735.0,...,171637514.0,167412698.0,56148976.0,17739183.0,7817044.0,1962301.0,1531219.0,00-00000-20190102,0,1
2,National,1/3/2019,NaN,NaN,NaN,NaN,63050480.0,263116940.0,1.162753e+09,296375014.0,...,175775410.0,172027487.0,57632422.0,18366626.0,8124548.0,2038099.0,1567072.0,00-00000-20190103,0,1
3,National,1/4/2019,NaN,NaN,NaN,NaN,61803652.0,264363768.0,1.181954e+09,293159631.0,...,181324645.0,176144493.0,58761592.0,19315785.0,8687318.0,2096065.0,1569185.0,00-00000-20190104,0,1
4,National,1/5/2019,NaN,NaN,NaN,NaN,64389745.0,261777675.0,1.180477e+09,295459014.0,...,180941769.0,165239790.0,54842134.0,19363939.0,8490791.0,1991159.0,1438664.0,00-00000-20190105,0,1

In [6]:
td.columns          # displays columns names

Index(['Level', 'Date', 'State FIPS', 'State Postal Code', 'County FIPS',
       'County Name', 'Population Staying at Home',
       'Population Not Staying at Home', 'Number of Trips',
       'Number of Trips <1', 'Number of Trips 1-3', 'Number of Trips 3-5',
       'Number of Trips 5-10', 'Number of Trips 10-25',
       'Number of Trips 25-50', 'Number of Trips 50-100',
       'Number of Trips 100-250', 'Number of Trips 250-500',
       'Number of Trips >=500', 'Row ID', 'Week', 'Month'],
      dtype='object')

In [7]:
td.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 22 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   Level                           1048575 non-null  object
 1   Date                            1048575 non-null  object
 2   State FIPS                      1047674 non-null  float64
 3   State Postal Code               1047674 non-null  object
 4   County FIPS                     1001723 non-null  float64
 5   County Name                     1001723 non-null  object
 6   Population Staying at Home      1035625 non-null  float64
 7   Population Not Staying at Home  1035625 non-null  float64
 8   Number of Trips                 1035625 non-null  float64
 9   Number of Trips <1              1035625 non-null  float64
 10  Number of Trips 1-3             1035625 non-null  float64
 11  Number of Trips 3-5             1035625 non-null  float64
 12  Number of Trips 5-10            1035625 non-null  float64
 13  Number of Trips 10-25           1035625 non-null  float64
 14  Number of Trips 25-50           1035625 non-null  float64
 15  Number of Trips 50-100          1035625 non-null  float64
 16  Number of Trips 100-250         1035625 non-null  float64
 17  Number of Trips 250-500         1035625 non-null  float64
 18  Number of Trips >=500           1035625 non-null  float64
 19  Row ID                          1048575 non-null  object
 20  Week                            1048575 non-null  int64
 21  Month                           1048575 non-null  int64
dtypes: float64(15), int64(2), object(5)
memory usage: 176.0+ MB

In [18]:
td.dtypes

level                              object
date                               object
state_fips                        float64
state_postal_code                  object
county_fips                       float64
county_name                        object
population_staying_at_home        float64
population_not_staying_at_home    float64
number_of_trips                   float64
number_of_trips_<1                float64
number_of_trips_1-3               float64
number_of_trips_3-5               float64
number_of_trips_5-10              float64
number_of_trips_10-25             float64
number_of_trips_25-50             float64
number_of_trips_50-100            float64
number_of_trips_100-250           float64
number_of_trips_250-500           float64
number_of_trips_>=500             float64
row_id                             object
week                                int64
month                               int64
dtype: object

In [8]:
td.columns = (td.columns.str.strip().str.lower().str.replace(" ","_"))
td = td.fillna(td.mean(numeric_only=True)) # fills missing numeric values with its mean

In [9]:
# handles missing categorical values
td["state_postal_code"] = td["state_postal_code"].fillna("Unknown")
td["county_name"] = td["county_name"].fillna("Unknown")

In [10]:
tf.columns = (tf.columns.str.strip().str.lower().str.replace(" ","_"))

In [11]:
tf.columns

Index(['month_of_date', 'week_of_date', 'year_of_date', 'level', 'date',
       'week_ending_date', 'trips_<1_mile', 'people_not_staying_at_home',
       'population_staying_at_home', 'trips', 'trips_1-25_miles',
       'trips_1-3_miles', 'trips_10-25_miles', 'trips_100-250_miles',
       'trips_100+_miles', 'trips_25-100_miles', 'trips_25-50_miles',
       'trips_250-500_miles', 'trips_3-5_miles', 'trips_5-10_miles',
       'trips_50-100_miles', 'trips_500+_miles'],
      dtype='object')

In [15]:
tf.head()

,month_of_date,week_of_date,year_of_date,level,date,week_ending_date,trips_<1_mile,people_not_staying_at_home,population_staying_at_home,trips,...,trips_10-25_miles,trips_100-250_miles,trips_100+_miles,trips_25-100_miles,trips_25-50_miles,trips_250-500_miles,trips_3-5_miles,trips_5-10_miles,trips_50-100_miles,trips_500+_miles
0,August,Week 32,2019,National,8/4/2019 0:00,10-Aug-19,292959749,258404133,67763287,1322685497,...,200922270,8595827,15338786,79429125,59517188,2273613,171336406,216121882,19911937,4469346
1,August,Week 32,2019,National,8/5/2019 0:00,10-Aug-19,317133861,262199758,63967662,1412564488,...,228809869,6535920,12563068,86004297,68184743,1941260,178996059,231048425,17819554,4085888
2,August,Week 32,2019,National,8/6/2019 0:00,10-Aug-19,324443205,260096133,66071287,1437762102,...,235621127,5993704,11104823,87599579,70149166,1741994,179210645,233248732,17450413,3369125
3,August,Week 32,2019,National,8/7/2019 0:00,10-Aug-19,358483024,258878802,67288618,1543710309,...,249988663,5379881,8528574,92200386,74381367,1272248,189163336,243872277,17819019,1876445
4,August,Week 32,2019,National,8/8/2019 0:00,10-Aug-19,300765870,262410045,63757375,1382044815,...,226055368,6259735,12892348,84193587,66724543,1957888,179346163,230933709,17469044,4674725

In [16]:
tf.columns

Index(['month_of_date', 'week_of_date', 'year_of_date', 'level', 'date',
       'week_ending_date', 'trips_<1_mile', 'people_not_staying_at_home',
       'population_staying_at_home', 'trips', 'trips_1-25_miles',
       'trips_1-3_miles', 'trips_10-25_miles', 'trips_100-250_miles',
       'trips_100+_miles', 'trips_25-100_miles', 'trips_25-50_miles',
       'trips_250-500_miles', 'trips_3-5_miles', 'trips_5-10_miles',
       'trips_50-100_miles', 'trips_500+_miles'],
      dtype='object')

In [17]:
tf.dtypes

month_of_date                 object
week_of_date                  object
year_of_date                   int64
level                         object
date                          object
week_ending_date              object
trips_<1_mile                  int64
people_not_staying_at_home     int64
population_staying_at_home     int64
trips                          int64
trips_1-25_miles               int64
trips_1-3_miles                int64
trips_10-25_miles              int64
trips_100-250_miles            int64
trips_100+_miles               int64
trips_25-100_miles             int64
trips_25-50_miles              int64
trips_250-500_miles            int64
trips_3-5_miles                int64
trips_5-10_miles               int64
trips_50-100_miles             int64
trips_500+_miles               int64
dtype: object